version: '3.7'

services:
  db:
    image: mysql:8.0
    container_name: go-grocery-db
    environment:
      MYSQL_DATABASE: 'go_grocery_local'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306
    volumes:
      - go-grocery-db:/var/lib/mysql
    networks:
      - go-grocery
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --character-set-client-handshake=FALSE #Set utf8mb4

volumes:
  go-grocery-db: ~

networks:
  go-grocery:
    name: go-grocery-api
